[params]
  hugo = "Rocks"

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-jslibs/alpinejs"
  [[module.mounts]]
    source = "templates/hooks"
    target = "layouts/_default/_markup"
  [[module.mounts]]
    source = 'static'
    target = 'static'
